version: "3"
services:

  web1:
    restart: on-failure
    build: ./web
    ports:
      - "81:5000"   
    

  web2:
    restart: on-failure
    build: ./web 
    ports:
      - "82:5000"  
  
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web1
      - web2